name: Lint JSON Schema

runs:
  using: "composite"
  steps:
    - name: Set up check-jsonschema
      shell: bash
      run: |
        pip install check-jsonschema

    - name: Verify meta schema
      shell: bash
      run: |
        # We handle the return code ourselves to prevent the action from exiting on the first error
        rc=0

        while read -r file; do
          if ! check-jsonschema --check-metaschema "$file"; then
            rc=1
          fi
        done < <(find src/schema -name "*.json")

        exit $rc
        