name: Lint JSON Schema

runs:
  using: "composite"
  steps:
    - name: Set up check-jsonschema
      shell: bash
      run: |
        pip install check-jsonschema

    - name: Verify schemas
      shell: bash
      run: |
        # We handle the return code ourselves to prevent the action from exiting on the first error
        rc=0

        while read -r file; do
          echo "Validating $file"
          if ! check-jsonschema --check-metaschema "$file"; then
            rc=1
          fi
        done < <(find src/schema -name "*.json" -maxdepth 1)

        exit $rc

    - name: Verify examples
      shell: bash
      run: |
        # We handle the return code ourselves to prevent the action from exiting on the first error
        rc=0

        cd src/schema/examples

        while read -r file; do
          schema=../${file%%.*}.json
          echo "Validating $file against $schema"
          if ! check-jsonschema --schemafile "$schema" "$file"; then
            rc=1
          fi
        done < <(find . -name "*.json" -maxdepth 1)

        exit $rc
        