name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  drawio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify number of diagrams
        run: |
          rc=0

          while read -r file; do
            if [[ $(grep "<diag" "$file" | wc -l) -ne 1 ]]; then
              >&2 echo "$file should contain exactly one diagram"
              rc=1
            fi
          done < <(find . -name "*.drawio")

          exit $rc