name: Lint

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  asciidoc:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/actions/lint-asciidoc

  drawio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/actions/lint-drawio

  plantuml:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/actions/lint-plantuml